state_collector_node:
  ros__parameters:
    rl_state_topic: /rl_state

task_manager_node:
  ros__parameters:
    selected_action_topic: /selected_action
    execute_command_topic: /execute_command

robot_executor_node:
  ros__parameters:
    joint_command_topic: /joint_command
    gripper_command_topic: /gripper_command

