vision_ai_node:
  ros__parameters:
    image_topic: /camera/image_raw
    depth_topic: /camera/depth/image_raw

object_pose_node:
  ros__parameters:
    detected_object_topic: /detected_object
    object_pose_topic: /object_pose

rl_policy_node:
  ros__parameters:
    rl_state_topic: /rl_state
    selected_action_topic: /selected_action

